# Autogenerated! DO NOT EDIT!
# This justfile is autogenerated via https://std.divnix.com/reference/std/nixago/just.html
# It can be used without Nix by running a locally installed  `just` binary.
# NOTE: Without Nix, you are responsible for having all task dependencies
# available locally!

# edit the key age with ragenix
age cell file:
    ragenix --edit ./nix/{{ cell }}/secretProfiles/{{ file }} --rules ./nix/{{ cell }}/secretProfiles/secrets.nix

# re-age key with ragenix
age-rekey cell:
    ragenix --rules ./nix/{{ cell }}/secretProfiles/secrets.nix --rekey

# build darwin machine
darwin-build machine:
    darwin-rebuild build --flake .#guangtao-o-{{ machine }}

# Colmena build Guangtao Home Machine
desktop action:
    colmena {{ action }} --on guangtao-o-desktop

# Formats all changed source files
fmt:
    treefmt $(git diff --name-only --cached)

# Colmena build Guangtao Libvirtd Machine
libvirtd_1:
    colmena build --on guangtao-o-libvirtd_1

# update sources with nvfetcher
nvfetcher path:
    nix develop github:GTrunSec/cells-lab#update --refresh --command nvfetcher-update {{ path }}/sources.toml

# update default toolchain with nvfetcher
nvfetcher-default:
    nix develop github:GTrunSec/cells-lab#update --refresh --command nvfetcher-update nix/guangtao/packages/./sources.toml

# update emacs toolchain with nvfetcher
nvfetcher-emacs:
    nix develop github:GTrunSec/cells-lab#update --refresh --command nvfetcher-update nix/guangtao/packages/emacs/sources.toml

# update packages via nvfetcher
nvfetcher-update cell:
    nix develop github:GTrunSec/cells-lab#devShells.x86_64-linux.update --refresh --command nvfetcher-update nix/{{ cell }}/packages/sources.toml
