# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  HPI = {
    pname = "HPI";
    version = "0.3.20230209";
    src = fetchurl {
      url = "https://pypi.io/packages/source/H/HPI/HPI-0.3.20230209.tar.gz";
      sha256 = "sha256-lSAj8UDOgaefqerxneRYpu0nezMg2K4eR5zkfU0mVjk=";
    };
  };
  StevenBlack-hosts = {
    pname = "StevenBlack-hosts";
    version = "543acefaf78eb06f9f99cac0b6b6b1f6d09f4f50";
    src = fetchFromGitHub ({
      owner = "StevenBlack";
      repo = "hosts";
      rev = "543acefaf78eb06f9f99cac0b6b6b1f6d09f4f50";
      fetchSubmodules = false;
      sha256 = "sha256-Afpvl/UnyyY0doqJJkli6Pg+tQYm69gU6cPSyht3YhQ=";
    });
    date = "2023-02-16";
  };
  adguardhome = {
    pname = "adguardhome";
    version = "v0.107.24";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.24/AdGuardHome_linux_amd64.tar.gz";
      sha256 = "sha256-cQMKUL5RT+CJiCwXnOPc9o0AwDmo0Z6X8L8TjWTKwpY=";
    };
  };
  brave = {
    pname = "brave";
    version = "1.48.164";
    src = fetchurl {
      url = "https://github.com/brave/brave-browser/releases/download/v1.48.164/brave-browser_1.48.164_amd64.deb";
      sha256 = "sha256-aZqxMx1hbk5vkVMETsoSvn5cgc9jYUeMWfRwCN5s/c0=";
    };
  };
  chatgpt-wrapper = {
    pname = "chatgpt-wrapper";
    version = "7c3f073ea0fa19d438bc46c923fd2463f1580c0f";
    src = fetchFromGitHub ({
      owner = "mmabrouk";
      repo = "chatgpt-wrapper";
      rev = "7c3f073ea0fa19d438bc46c923fd2463f1580c0f";
      fetchSubmodules = false;
      sha256 = "sha256-yR9SZuuQN2gFiLNNiqycA3FBI8bmJ2P7LjwAWXpX4Mc=";
    });
    date = "2023-02-16";
  };
  chord = {
    pname = "chord";
    version = "0.2.38";
    src = fetchurl {
      url = "https://github.com/PeterDing/chord/releases/download/v0.2.38/chord-0.2.38-linux-x86_64.AppImage";
      sha256 = "sha256-14rkxceyS0OwnOK14rICWnzLLkRB8dmqRkPq829znws=";
    };
  };
  drawio = {
    pname = "drawio";
    version = "20.8.16";
    src = fetchurl {
      url = "https://github.com/jgraph/drawio-desktop/releases/download/v20.8.16/drawio-x86_64-20.8.16.rpm";
      sha256 = "sha256-FBnyogqf5BHLRInjJzC2dENnAwFcWMHDvJ+F0I3ffVg=";
    };
  };
  hug = {
    pname = "hug";
    version = "2.6.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/h/hug/hug-2.6.1.tar.gz";
      sha256 = "sha256-sO2s4qy2GIc3ecnObs+RZdtU/vlcIiYvVwD83Z/rrsk=";
    };
  };
  logseq = {
    pname = "logseq";
    version = "0.8.17";
    src = fetchurl {
      url = "https://github.com/logseq/logseq/releases/download/0.8.17/logseq-linux-x64-0.8.17.AppImage";
      sha256 = "sha256-z7v59wXvSIDC7f4IMT8bblPgn+3+J54XqIPzXqWDses=";
    };
  };
  logseq-darwin = {
    pname = "logseq-darwin";
    version = "0.8.17";
    src = fetchurl {
      url = "https://github.com/logseq/logseq/releases/download/0.8.17/logseq-darwin-x64-0.8.17.dmg";
      sha256 = "sha256-5ghhbTbPGxV/z/N8kqQXlm4WIMETGAAd0gKTnFOW6P8=";
    };
  };
  magnetw = {
    pname = "magnetw";
    version = "3.1.1";
    src = fetchurl {
      url = "https://github.com/xiandanin/magnetW/releases/download/3.1.1/magnetw-3.1.1-linux.AppImage";
      sha256 = "sha256-ie6XGdd/HQCxIaLY5gGOgOXCHDJxcnaxgaO7plA5Eh8=";
    };
  };
  motrix = {
    pname = "motrix";
    version = "1.6.11";
    src = fetchurl {
      url = "https://github.com/agalwood/Motrix/releases/download/v1.6.11/Motrix-1.6.11.AppImage";
      sha256 = "sha256-tE2Q7NM+cQOg+vyqyfRwg05EOMQWhhggTA6S+VT+SkM=";
    };
  };
  orgparse = {
    pname = "orgparse";
    version = "0.3.2";
    src = fetchurl {
      url = "https://pypi.io/packages/source/o/orgparse/orgparse-0.3.2.tar.gz";
      sha256 = "sha256-RRBQ55rLelHGXcmbkJXq5NUL1ZhUE1T552PLTL31mlU=";
    };
  };
  promnesia = {
    pname = "promnesia";
    version = "c52cdde324651773b0119ae77fa45113fa1814e5";
    src = fetchFromGitHub ({
      owner = "karlicoss";
      repo = "promnesia";
      rev = "c52cdde324651773b0119ae77fa45113fa1814e5";
      fetchSubmodules = false;
      sha256 = "sha256-Of7Tfcgu891S04wria+fwggm59mMsZsCYE0r5Gs0Kz0=";
    });
    date = "2023-02-13";
  };
  spaceship-prompt = {
    pname = "spaceship-prompt";
    version = "695f4d63ae2f0fecc6d006947f8acc374b2697a0";
    src = fetchFromGitHub ({
      owner = "spaceship-prompt";
      repo = "spaceship-prompt";
      rev = "695f4d63ae2f0fecc6d006947f8acc374b2697a0";
      fetchSubmodules = false;
      sha256 = "sha256-9vBqTVkXfoIGcIe2DcGwSqe/5w+NoMcbDOftSnHbgrc=";
    });
    date = "2023-02-09";
  };
  wezterm-appimage = {
    pname = "wezterm-appimage";
    version = "02-16-2023";
    src = fetchurl {
      url = "https://github.com/wez/wezterm/releases/download/nightly/WezTerm-nightly-Ubuntu18.04.AppImage";
      sha256 = "sha256-pXvURQjmmE653mkQMGCzH+gZUMv1T6f3/lRxaQaqAvQ=";
    };
  };
  wezterm-darwin = {
    pname = "wezterm-darwin";
    version = "date +%m-%d-%Y";
    src = fetchurl {
      url = "https://github.com/wez/wezterm/releases/download/nightly/WezTerm-macos-nightly.zip";
      sha256 = "sha256-nObfSq1fTG7iu8/t3D3qJvem8Ho292oQhH92L7w+Fu4=";
    };
  };
}
