# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  HPI = {
    pname = "HPI";
    version = "0.3.20220607";
    src = fetchurl {
      url = "https://pypi.io/packages/source/H/HPI/HPI-0.3.20220607.tar.gz";
      sha256 = "sha256-GME0Z+TH/6U+smFkuk1sT8UBzlySv5/yGhb42Kiaj8w=";
    };
  };
  StevenBlack-hosts = {
    pname = "StevenBlack-hosts";
    version = "47d6b2a17b7b7558fa0915fc6497c03232ce3580";
    src = fetchFromGitHub ({
      owner = "StevenBlack";
      repo = "hosts";
      rev = "47d6b2a17b7b7558fa0915fc6497c03232ce3580";
      fetchSubmodules = false;
      sha256 = "sha256-dkYKi2P8qLoCe2SlVmaB1dIZze8cnuHs5vuTapxL7x8=";
    });
    date = "2023-01-13";
  };
  adguardhome = {
    pname = "adguardhome";
    version = "v0.107.21";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.21/AdGuardHome_linux_amd64.tar.gz";
      sha256 = "sha256-xU5PxscqBEGNCgA241UbhJcxlNXpCxbFeU7bfmSqf7I=";
    };
  };
  brave = {
    pname = "brave";
    version = "1.47.171";
    src = fetchurl {
      url = "https://github.com/brave/brave-browser/releases/download/v1.47.171/brave-browser_1.47.171_amd64.deb";
      sha256 = "sha256-0hKosta1fxth9ScDRmrrt8BH4CTIRm0ghetY4Jkuco8=";
    };
  };
  chord = {
    pname = "chord";
    version = "0.2.38";
    src = fetchurl {
      url = "https://github.com/PeterDing/chord/releases/download/v0.2.38/chord-0.2.38-linux-x86_64.AppImage";
      sha256 = "sha256-14rkxceyS0OwnOK14rICWnzLLkRB8dmqRkPq829znws=";
    };
  };
  drawio = {
    pname = "drawio";
    version = "20.7.4";
    src = fetchurl {
      url = "https://github.com/jgraph/drawio-desktop/releases/download/v20.7.4/drawio-x86_64-20.7.4.rpm";
      sha256 = "sha256-gmC8s+0eef09wcLE9fBiG82rRPXijRyR1WTlp4gYPq4=";
    };
  };
  hug = {
    pname = "hug";
    version = "2.6.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/h/hug/hug-2.6.1.tar.gz";
      sha256 = "sha256-sO2s4qy2GIc3ecnObs+RZdtU/vlcIiYvVwD83Z/rrsk=";
    };
  };
  kitty-darwin = {
    pname = "kitty-darwin";
    version = "0.26.5";
    src = fetchurl {
      url = "https://github.com/kovidgoyal/kitty/releases/download/v0.26.5/kitty-0.26.5.dmg";
      sha256 = "sha256-bh3P6/0NHEwuv8+96+aIr9CKQHfErADbS1B/7ukwc1M=";
    };
  };
  logseq = {
    pname = "logseq";
    version = "0.8.16";
    src = fetchurl {
      url = "https://github.com/logseq/logseq/releases/download/0.8.16/logseq-linux-x64-0.8.16.AppImage";
      sha256 = "sha256-0tIDoNQoqSn1nYm+YdgzXh34aH1e5N8wl9lqGbQoOeU=";
    };
  };
  logseq-darwin = {
    pname = "logseq-darwin";
    version = "0.8.16";
    src = fetchurl {
      url = "https://github.com/logseq/logseq/releases/download/0.8.16/logseq-darwin-x64-0.8.16.dmg";
      sha256 = "sha256-RsHmZjNpsvX6zJBdVeEZj1ntKoCWC7dR19MFve3U4rE=";
    };
  };
  magnetw = {
    pname = "magnetw";
    version = "3.1.1";
    src = fetchurl {
      url = "https://github.com/xiandanin/magnetW/releases/download/3.1.1/magnetw-3.1.1-linux.AppImage";
      sha256 = "sha256-ie6XGdd/HQCxIaLY5gGOgOXCHDJxcnaxgaO7plA5Eh8=";
    };
  };
  motrix = {
    pname = "motrix";
    version = "1.6.11";
    src = fetchurl {
      url = "https://github.com/agalwood/Motrix/releases/download/v1.6.11/Motrix-1.6.11.AppImage";
      sha256 = "sha256-tE2Q7NM+cQOg+vyqyfRwg05EOMQWhhggTA6S+VT+SkM=";
    };
  };
  orgparse = {
    pname = "orgparse";
    version = "0.3.2";
    src = fetchurl {
      url = "https://pypi.io/packages/source/o/orgparse/orgparse-0.3.2.tar.gz";
      sha256 = "sha256-RRBQ55rLelHGXcmbkJXq5NUL1ZhUE1T552PLTL31mlU=";
    };
  };
  promnesia = {
    pname = "promnesia";
    version = "9a2efdf8a30c6a9dd243dfba76039e01e8b9490f";
    src = fetchFromGitHub ({
      owner = "karlicoss";
      repo = "promnesia";
      rev = "9a2efdf8a30c6a9dd243dfba76039e01e8b9490f";
      fetchSubmodules = false;
      sha256 = "sha256-eNXYqBwqUOTyl/ejk1AYg2PN3TANk8LI2HHyK+i0q9o=";
    });
    date = "2023-01-12";
  };
  spaceship-prompt = {
    pname = "spaceship-prompt";
    version = "f1744472babdc801e1806b663409facd84ecfa25";
    src = fetchFromGitHub ({
      owner = "spaceship-prompt";
      repo = "spaceship-prompt";
      rev = "f1744472babdc801e1806b663409facd84ecfa25";
      fetchSubmodules = false;
      sha256 = "sha256-hJWgOcsYnyY+EyFSnfhDro16RjSSDFOeg6M2luA3r3g=";
    });
    date = "2023-01-11";
  };
}
