# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  HPI = {
    pname = "HPI";
    version = "0.3.20220607";
    src = fetchurl {
      url = "https://pypi.io/packages/source/H/HPI/HPI-0.3.20220607.tar.gz";
      sha256 = "sha256-GME0Z+TH/6U+smFkuk1sT8UBzlySv5/yGhb42Kiaj8w=";
    };
  };
  StevenBlack-hosts = {
    pname = "StevenBlack-hosts";
    version = "f91285ebe73d82b48875aee2fcd06c20f4566e12";
    src = fetchFromGitHub ({
      owner = "StevenBlack";
      repo = "hosts";
      rev = "f91285ebe73d82b48875aee2fcd06c20f4566e12";
      fetchSubmodules = false;
      sha256 = "sha256-BRAitGAtzk4gGDZ7+K3FBS81D/8cwkVLRQkccMBhBLQ=";
    });
    date = "2023-01-01";
  };
  adguardhome = {
    pname = "adguardhome";
    version = "v0.107.21";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.21/AdGuardHome_linux_amd64.tar.gz";
      sha256 = "sha256-xU5PxscqBEGNCgA241UbhJcxlNXpCxbFeU7bfmSqf7I=";
    };
  };
  chord = {
    pname = "chord";
    version = "0.2.38";
    src = fetchurl {
      url = "https://github.com/PeterDing/chord/releases/download/v0.2.38/chord-0.2.38-linux-x86_64.AppImage";
      sha256 = "sha256-14rkxceyS0OwnOK14rICWnzLLkRB8dmqRkPq829znws=";
    };
  };
  drawio = {
    pname = "drawio";
    version = "20.7.4";
    src = fetchurl {
      url = "https://github.com/jgraph/drawio-desktop/releases/download/v20.7.4/drawio-x86_64-20.7.4.rpm";
      sha256 = "sha256-gmC8s+0eef09wcLE9fBiG82rRPXijRyR1WTlp4gYPq4=";
    };
  };
  hug = {
    pname = "hug";
    version = "2.6.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/h/hug/hug-2.6.1.tar.gz";
      sha256 = "sha256-sO2s4qy2GIc3ecnObs+RZdtU/vlcIiYvVwD83Z/rrsk=";
    };
  };
  kitty-darwin = {
    pname = "kitty-darwin";
    version = "0.26.5";
    src = fetchurl {
      url = "https://github.com/kovidgoyal/kitty/releases/download/v0.26.5/kitty-0.26.5.dmg";
      sha256 = "sha256-bh3P6/0NHEwuv8+96+aIr9CKQHfErADbS1B/7ukwc1M=";
    };
  };
  logseq = {
    pname = "logseq";
    version = "0.8.15";
    src = fetchurl {
      url = "https://github.com/logseq/logseq/releases/download/0.8.15/logseq-linux-x64-0.8.15.AppImage";
      sha256 = "sha256-lE/bO/zpqChvdf8vfNqbC5iIpXAZDb36/N7Tpsj7PWY=";
    };
  };
  logseq-darwin = {
    pname = "logseq-darwin";
    version = "0.8.15";
    src = fetchurl {
      url = "https://github.com/logseq/logseq/releases/download/0.8.15/logseq-darwin-x64-0.8.15.dmg";
      sha256 = "sha256-0IgycMWpXQEtp0Twbwvps4/vEXmq3d5ayHS9W1DAxNE=";
    };
  };
  magnetw = {
    pname = "magnetw";
    version = "3.1.1";
    src = fetchurl {
      url = "https://github.com/xiandanin/magnetW/releases/download/3.1.1/magnetw-3.1.1-linux.AppImage";
      sha256 = "sha256-ie6XGdd/HQCxIaLY5gGOgOXCHDJxcnaxgaO7plA5Eh8=";
    };
  };
  motrix = {
    pname = "motrix";
    version = "1.6.11";
    src = fetchurl {
      url = "https://github.com/agalwood/Motrix/releases/download/v1.6.11/Motrix-1.6.11.AppImage";
      sha256 = "sha256-tE2Q7NM+cQOg+vyqyfRwg05EOMQWhhggTA6S+VT+SkM=";
    };
  };
  orgparse = {
    pname = "orgparse";
    version = "0.3.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/o/orgparse/orgparse-0.3.1.tar.gz";
      sha256 = "sha256-hg5vu5pnt0K6p5LmD4zBhSLpeJwGXSaCHAIoXV/BBK8=";
    };
  };
  promnesia = {
    pname = "promnesia";
    version = "3e788bb219c5b2ce5684d1222ff8d22010ca538d";
    src = fetchFromGitHub ({
      owner = "karlicoss";
      repo = "promnesia";
      rev = "3e788bb219c5b2ce5684d1222ff8d22010ca538d";
      fetchSubmodules = false;
      sha256 = "sha256-5PXoh7k05b/5UvQ0HxONFSHvzrGemod8duUVTM1auoM=";
    });
    date = "2023-01-02";
  };
  spaceship-prompt = {
    pname = "spaceship-prompt";
    version = "96a07d922ad9de198c475f82ec1570cbf81e64d1";
    src = fetchFromGitHub ({
      owner = "spaceship-prompt";
      repo = "spaceship-prompt";
      rev = "96a07d922ad9de198c475f82ec1570cbf81e64d1";
      fetchSubmodules = false;
      sha256 = "sha256-S21lv6g7GeODWcJjdOp4DLXDX/TQY53PZEvFCPdtVmw=";
    });
    date = "2023-01-02";
  };
}
