[tool.poetry]
name = "mind-wave"
version = "0.1.0"
description = ""
authors = ["guangtao <gtrunsec@hardenedlinux.org>"]
readme = "README.md"
packages = [{ include = "mind_wave" }]

[tool.poetry.dependencies]
python = "^3.10"
openai = "^0.27.1"
epc = "^0.0.5"
sexpdata = "^1.0.0"
six = "^1.16.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
