# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  ...
}: {
  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];

  fileSystems."/DATABASE-4TB" = {
    device = "/dev/disk/by-uuid/749df476-c355-469a-9d00-4565a07901bf";
    options = ["x-systemd.automount"];
    fsType = "xfs";
  };

  fileSystems."/persist".neededForBoot = true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
