# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  ...
}: {
  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CF48-6C3C";
    fsType = "vfat";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a8b91326-9a5f-47c9-b827-19e1ce17cfe8";
    fsType = "xfs";
  };
  ##sudo blkid
  fileSystems."/SSD-1TB" = {
    device = "/dev/disk/by-uuid/ae748e00-3013-4c27-8824-a1d36631cf34";
    options = ["x-systemd.automount"];
    fsType = "xfs";
  };

  swapDevices = [{device = "/dev/disk/by-uuid/d05ef9fb-1433-4819-b1a7-e15b5a7b9a90";}];

  fileSystems."/DATABASE-4TB" = {
    device = "/dev/disk/by-uuid/749df476-c355-469a-9d00-4565a07901bf";
    options = ["x-systemd.automount"];
    fsType = "xfs";
  };

  nix.maxJobs = lib.mkDefault 12;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
