# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  GodTian_Pinyin = {
    pname = "GodTian_Pinyin";
    version = "e21e41510b6d440389966bb0b2a70b38fafc6741";
    src = fetchFromGitHub ({
      owner = "whatbeg";
      repo = "GodTian_Pinyin";
      rev = "e21e41510b6d440389966bb0b2a70b38fafc6741";
      fetchSubmodules = false;
      sha256 = "sha256-uSrj+hwai7fSJN7SWL5u80hp8nSzJ4XI5t/8s19uoV8=";
    });
    date = "2017-07-19";
  };
  acm-terminal = {
    pname = "acm-terminal";
    version = "321e05fc0398a6159925b858f46608ea07ef269e";
    src = fetchFromGitHub ({
      owner = "twlz0ne";
      repo = "acm-terminal";
      rev = "321e05fc0398a6159925b858f46608ea07ef269e";
      fetchSubmodules = false;
      sha256 = "sha256-Flw07EwH9z0E3tqXs4mStICJmoHfp60ALrP1GmUmeuU=";
    });
    date = "2023-02-15";
  };
  jinx = {
    pname = "jinx";
    version = "397112434c3ca0f6c9a201b73eeaf19c8dc11d8e";
    src = fetchFromGitHub ({
      owner = "minad";
      repo = "jinx";
      rev = "397112434c3ca0f6c9a201b73eeaf19c8dc11d8e";
      fetchSubmodules = false;
      sha256 = "sha256-HNeXiQmxGO4h7bNSou9tq4I3TQZsCAtZSbpf4grFGWc=";
    });
    date = "2023-03-30";
  };
  lsp-bridge = {
    pname = "lsp-bridge";
    version = "fe8e1b639f83e2ab580302c7041e11b32eb64deb";
    src = fetchFromGitHub ({
      owner = "manateelazycat";
      repo = "lsp-bridge";
      rev = "fe8e1b639f83e2ab580302c7041e11b32eb64deb";
      fetchSubmodules = false;
      sha256 = "sha256-fL+PO+rbmwerzghdc/HWjs/HVZWRZQsk/M172hAhtME=";
    });
    date = "2023-03-30";
  };
}
