# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  acm-terminal = {
    pname = "acm-terminal";
    version = "8560abb3d951a73782e64dd1b1333c5a60ea28d4";
    src = fetchFromGitHub ({
      owner = "twlz0ne";
      repo = "acm-terminal";
      rev = "8560abb3d951a73782e64dd1b1333c5a60ea28d4";
      fetchSubmodules = false;
      sha256 = "sha256-HIRlG9DcazA7wN7dNCJ3meZ51fLxJtSu4fajMigEhAQ=";
    });
    date = "2022-12-04";
  };
}
