# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  GodTian_Pinyin = {
    pname = "GodTian_Pinyin";
    version = "e21e41510b6d440389966bb0b2a70b38fafc6741";
    src = fetchFromGitHub ({
      owner = "whatbeg";
      repo = "GodTian_Pinyin";
      rev = "e21e41510b6d440389966bb0b2a70b38fafc6741";
      fetchSubmodules = false;
      sha256 = "sha256-uSrj+hwai7fSJN7SWL5u80hp8nSzJ4XI5t/8s19uoV8=";
    });
    date = "2017-07-19";
  };
  acm-terminal = {
    pname = "acm-terminal";
    version = "321e05fc0398a6159925b858f46608ea07ef269e";
    src = fetchFromGitHub ({
      owner = "twlz0ne";
      repo = "acm-terminal";
      rev = "321e05fc0398a6159925b858f46608ea07ef269e";
      fetchSubmodules = false;
      sha256 = "sha256-Flw07EwH9z0E3tqXs4mStICJmoHfp60ALrP1GmUmeuU=";
    });
    date = "2023-02-15";
  };
  jinx = {
    pname = "jinx";
    version = "2f7f4ac9ce3f69a0d086e2600406c36f46ff3a07";
    src = fetchFromGitHub ({
      owner = "minad";
      repo = "jinx";
      rev = "2f7f4ac9ce3f69a0d086e2600406c36f46ff3a07";
      fetchSubmodules = false;
      sha256 = "sha256-SWWXd5/7QyYxg4TFUjIh5e/GHWbVCZI8aWXbom/v/fI=";
    });
    date = "2023-04-20";
  };
  lsp-bridge = {
    pname = "lsp-bridge";
    version = "6725242fc9b82a7ec6d99640dfdd32dc6cb1bc03";
    src = fetchFromGitHub ({
      owner = "manateelazycat";
      repo = "lsp-bridge";
      rev = "6725242fc9b82a7ec6d99640dfdd32dc6cb1bc03";
      fetchSubmodules = false;
      sha256 = "sha256-rSkSI/Aflv9WY5pW5F9DtmZ62cYEJV8Df3qeiKHZHcE=";
    });
    date = "2023-04-21";
  };
}
