# Avoid to override default key-bindings
#
# Control + B ⇒ SearchBackward
# Control + C ⇒ Copy
# Control + F ⇒ SearchForward
# Control + V ⇒ Paste
# Control + 0 ⇒ ResetFontSize
#
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml
[[key_bindings]]
key = "H"
mods = "Control"
chars = "\u001b[104;5u"

[[key_bindings]]
key = "H"
mods = "Control|Alt"
chars = "\u001b[104;7u"

[[key_bindings]]
key = "I"
mods = "Control"
chars = "\u001b[105;5u"

[[key_bindings]]
key = "I"
mods = "Control|Alt"
chars = "\u001b[105;7u"

[[key_bindings]]
key = "J"
mods = "Control"
chars = "\u001b[106;5u"

[[key_bindings]]
key = "J"
mods = "Control|Alt"
chars = "\u001b[106;7u"

[[key_bindings]]
key = "M"
mods = "Control"
chars = "\u001b[109;5u"

[[key_bindings]]
key = "M"
mods = "Control|Alt"
chars = "\u001b[109;7u"

[[key_bindings]]
key = "O"
mods = "Shift|Alt"
chars = "\u001b[79;3u"

[[key_bindings]]
key = "Return"
mods = "Control"
chars = "\u001b[13;5u"

[[key_bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b[13;2u"

[[key_bindings]]
key = "Return"
mods = "Shift|Control"
chars = "\u001b[13;6u"

[[key_bindings]]
key = "Return"
mods = "Shift|Alt"
chars = "\u001b[13;4u"

[[key_bindings]]
key = "Return"
mods = "Alt|Control"
chars = "\u001b[13;7u"

[[key_bindings]]
key = "Return"
mods = "Shift|Alt|Control"
chars = "\u001b[13;8u"

# [[key_bindings]]
# key = "Slash"
# mods = "Control"
# chars = "\u001b[47;2u"
[[key_bindings]]
key = "Space"
mods = "Shift"
chars = "\u001b[32;2u"

# [[key_bindings]]
# key = "Space"
# mods = "Shift|Control"
# chars = "\u001b[32;6u"
[[key_bindings]]
key = "Space"
mods = "Shift|Alt"
chars = "\u001b[32;4u"

[[key_bindings]]
key = "Space"
mods = "Shift|Alt|Control"
chars = "\u001b[32;8u"

[[key_bindings]]
key = "Back"
mods = "Shift"
chars = "\u001b[127;2u"

[[key_bindings]]
key = "Back"
mods = "Control"
chars = "\u001b[127;5u"

[[key_bindings]]
key = "Back"
mods = "Shift|Control"
chars = "\u001b[127;6u"

[[key_bindings]]
key = "Back"
mods = "Shift|Alt"
chars = "\u001b[127;4u"

[[key_bindings]]
key = "Back"
mods = "Alt|Control"
chars = "\u001b[127;7u"

[[key_bindings]]
key = "Back"
mods = "Shift|Alt|Control"
chars = "\u001b[127;8u"

[[key_bindings]]
key = "Tab"
mods = "Control"
chars = "\u001b[9;5u"

[[key_bindings]]
key = "Tab"
mods = "Alt|Control"
chars = "\u001b[9;7u"

[[key_bindings]]
key = "Tab"
mods = "Shift|Alt"
chars = "\u001b[9;4u"

[[key_bindings]]
key = "Tab"
mods = "Shift|Control"
chars = "\u001b[9;6u"

[[key_bindings]]
key = "Tab"
mods = "Shift|Alt|Control"
chars = "\u001b[9;8u"

[[key_bindings]]
key = "Escape"
mods = "Alt"
chars = "\u001b[27;3u"

[[key_bindings]]
key = "Escape"
mods = "Control"
chars = "\u001b[27;5u"

[[key_bindings]]
key = "Escape"
mods = "Shift"
chars = "\u001b[27;2u"

[[key_bindings]]
key = "Escape"
mods = "Shift|Control"
chars = "\u001b[27;6u"

[[key_bindings]]
key = "Escape"
mods = "Shift|Alt"
chars = "\u001b[27;4u"

[[key_bindings]]
key = "Escape"
mods = "Alt|Control"
chars = "\u001b[27;7u"

[[key_bindings]]
key = "Escape"
mods = "Shift|Alt|Control"
chars = "\u001b[27;8u"

[[key_bindings]] # 1
key = 2
mods = "Control"
chars = "\u001b[49;5u"

[[key_bindings]] # 1
key = 2
mods = "Alt|Control"
chars = "\u001b[49;7u"

[[key_bindings]] # !
key = 2
mods = "Shift|Control"
chars = "\u001b[33;5u"

[[key_bindings]] # !
key = 2
mods = "Shift|Alt|Control"
chars = "\u001b[33;7u"

[[key_bindings]] # 2
key = 3
mods = "Control"
chars = "\u001b[50;5u"

[[key_bindings]] # 2
key = 3
mods = "Alt|Control"
chars = "\u001b[50;7u"

[[key_bindings]] # @
key = 3
mods = "Shift|Control"
chars = "\u001b[64;5u"

[[key_bindings]] # @
key = 3
mods = "Shift|Alt|Control"
chars = "\u001b[64;7u"

[[key_bindings]] # 3
key = 4
mods = "Control"
chars = "\u001b[51;5u"

[[key_bindings]] # 3
key = 4
mods = "Alt|Control"
chars = "\u001b[51;7u"

[[key_bindings]] # #
key = 4
mods = "Shift|Control"
chars = "\u001b[35;5u"

[[key_bindings]] # #
key = 4
mods = "Shift|Alt|Control"
chars = "\u001b[35;7u"

[[key_bindings]] # 4
key = 5
mods = "Control"
chars = "\u001b[52;5u"

[[key_bindings]] # 4
key = 5
mods = "Alt|Control"
chars = "\u001b[52;7u"

[[key_bindings]] # $
key = 5
mods = "Shift|Control"
chars = "\u001b[36;5u"

[[key_bindings]] # $
key = 5
mods = "Shift|Alt|Control"
chars = "\u001b[36;7u"

[[key_bindings]] # 5
key = 6
mods = "Control"
chars = "\u001b[53;5u"

[[key_bindings]] # 5
key = 6
mods = "Alt|Control"
chars = "\u001b[53;7u"

[[key_bindings]] # %
key = 6
mods = "Shift|Control"
chars = "\u001b[37;5u"

[[key_bindings]] # %
key = 6
mods = "Shift|Alt|Control"
chars = "\u001b[37;7u"

[[key_bindings]] # 6
key = 7
mods = "Control"
chars = "\u001b[54;5u"

[[key_bindings]] # 6
key = 7
mods = "Alt|Control"
chars = "\u001b[54;7u"

[[key_bindings]] # ^
key = 7
mods = "Shift|Control"
chars = "\u001b[94;5u"

[[key_bindings]] # ^
key = 7
mods = "Shift|Alt|Control"
chars = "\u001b[94;7u"

[[key_bindings]] # 7
key = 8
mods = "Control"
chars = "\u001b[55;5u"

[[key_bindings]] # 7
key = 8
mods = "Alt|Control"
chars = "\u001b[55;7u"

[[key_bindings]] # &
key = 8
mods = "Shift|Control"
chars = "\u001b[38;5u"

[[key_bindings]] # &
key = 8
mods = "Shift|Alt|Control"
chars = "\u001b[38;7u"

[[key_bindings]] # 8
key = 9
mods = "Control"
chars = "\u001b[56;5u"

[[key_bindings]] # 8
key = 9
mods = "Alt|Control"
chars = "\u001b[56;7u"

[[key_bindings]] # *
key = 9
mods = "Shift|Control"
chars = "\u001b[42;5u"

[[key_bindings]] # *
key = 9
mods = "Shift|Alt|Control"
chars = "\u001b[42;7u"

[[key_bindings]] # 9
key = 10
mods = "Control"
chars = "\u001b[57;5u"

[[key_bindings]] # 9
key = 10
mods = "Alt|Control"
chars = "\u001b[57;7u"

[[key_bindings]] # (
key = 10
mods = "Shift|Control"
chars = "\u001b[40;5u"

[[key_bindings]] # (
key = 10
mods = "Shift|Alt|Control"
chars = "\u001b[40;7u"

[[key_bindings]] # 0
key = 11
mods = "Control"
chars = "\u001b[48;5u"

[[key_bindings]] # 0
key = 11
mods = "Alt|Control"
chars = "\u001b[48;7u"

[[key_bindings]] # )
key = 11
mods = "Shift|Control"
chars = "\u001b[41;5u"

[[key_bindings]] # )
key = 11
mods = "Shift|Alt|Control"
chars = "\u001b[41;7u"

[[key_bindings]] # -
key = 12
mods = "Control"
chars = "\u001b[45;5u"

[[key_bindings]] # -
key = 12
mods = "Alt|Control"
chars = "\u001b[45;7u"

[[key_bindings]] # _
key = 12
mods = "Shift|Control"
chars = "\u001b[95;5u"

[[key_bindings]] # _
key = 12
mods = "Shift|Alt|Control"
chars = "\u001b[95;7u"

[[key_bindings]] # =
key = 13
mods = "Control"
chars = "\u001b[61;5u"

[[key_bindings]] # =
key = 13
mods = "Alt|Control"
chars = "\u001b[61;7u"

[[key_bindings]] # +
key = 13
mods = "Shift|Control"
chars = "\u001b[43;5u"

[[key_bindings]] # +
key = 13
mods = "Shift|Alt|Control"
chars = "\u001b[43;7u"

[[key_bindings]] # [
key = 26
mods = "Control"
chars = "\u001b[91;5u"

[[key_bindings]] # [
key = 26
mods = "Alt|Control"
chars = "\u001b[91;7u"

[[key_bindings]] # [
key = 26
mods = "Alt"
chars = "\u001b[91;3u"

[[key_bindings]] # {
key = 26
mods = "Shift|Control"
chars = "\u001b[123;5u"

[[key_bindings]] # {
key = 26
mods = "Shift|Alt|Control"
chars = "\u001b[123;7u"

[[key_bindings]] # ]
key = 27
mods = "Control"
chars = "\u001b[93;5u"

[[key_bindings]] # ]
key = 27
mods = "Alt|Control"
chars = "\u001b[93;7u"

[[key_bindings]] # }
key = 27
mods = "Shift|Control"
chars = "\u001b[125;5u"

[[key_bindings]] # }
key = 27
mods = "Shift|Alt|Control"
chars = "\u001b[125;7u"

[[key_bindings]] # '
key = 40
mods = "Control"
chars = "\u001b[39;5u"

[[key_bindings]] # '
key = 40
mods = "Alt|Control"
chars = "\u001b[39;7u"

[[key_bindings]] # "
key = 40
mods = "Shift|Control"
chars = "\u001b[34;5u"

[[key_bindings]] # "
key = 40
mods = "Shift|Alt|Control"
chars = "\u001b[34;7u"

[[key_bindings]] # `
key = 41
mods = "Control"
chars = "\u001b[96;5u"

[[key_bindings]] # `
key = 41
mods = "Alt|Control"
chars = "\u001b[96;7u"

[[key_bindings]] # ~
key = 41
mods = "Shift|Control"
chars = "\u001b[126;5u"

[[key_bindings]] # ~
key = 41
mods = "Shift|Alt|Control"
chars = "\u001b[126;7u"

[[key_bindings]] # ;
key = 39
mods = "Control"
chars = "\u001b[59;5u"

[[key_bindings]] # ;
key = 39
mods = "Alt|Control"
chars = "\u001b[59;7u"

[[key_bindings]] # :
key = 39
mods = "Shift|Control"
chars = "\u001b[58;5u"

[[key_bindings]] # :
key = 39
mods = "Shift|Alt|Control"
chars = "\u001b[58;7u"

[[key_bindings]] # /
key = 53
mods = "Control"
chars = "\u001b[47;5u"

[[key_bindings]] # /
key = 53
mods = "Alt|Control"
chars = "\u001b[47;7u"

[[key_bindings]] # ?
key = 53
mods = "Shift|Control"
chars = "\u001b[63;5u"

[[key_bindings]] # ?
key = 53
mods = "Shift|Alt|Control"
chars = "\u001b[63;7u"

[[key_bindings]] # ,
key = 51
mods = "Control"
chars = "\u001b[44;5u"

[[key_bindings]] # ,
key = 51
mods = "Alt|Control"
chars = "\u001b[44;7u"

[[key_bindings]] # <
key = 51
mods = "Shift|Control"
chars = "\u001b[60;5u"

[[key_bindings]] # <
key = 51
mods = "Shift|Alt|Control"
chars = "\u001b[60;7u"

[[key_bindings]] # .
key = 52
mods = "Control"
chars = "\u001b[46;5u"

[[key_bindings]] # .
key = 52
mods = "Alt|Control"
chars = "\u001b[46;7u"

[[key_bindings]] # >
key = 52
mods = "Shift|Control"
chars = "\u001b[62;5u"

[[key_bindings]] # >
key = 52
mods = "Shift|Alt|Control"
chars = "\u001b[62;7u"

[[key_bindings]]
key = "A"
mods = "Control|Shift"
chars = "\u001b[65;5u"

[[key_bindings]]
key = "A"
mods = "Control|Shift|Alt"
chars = "\u001b[65;7u"

# Control + B ⇒ SearchBackward
# [[key_bindings]]
# key = "B"
# mods = "Control|Shift"
# chars = "\u001b[66;5u"
[[key_bindings]]
key = "B"
mods = "Control|Shift|Alt"
chars = "\u001b[66;7u"

# Control + C ⇒ Copy
# [[key_bindings]]
# key = "C"
# mods = "Control|Shift"
# chars = "\u001b[67;5u"
[[key_bindings]]
key = "C"
mods = "Control|Shift|Alt"
chars = "\u001b[67;7u"

[[key_bindings]]
key = "D"
mods = "Control|Shift"
chars = "\u001b[68;5u"

[[key_bindings]]
key = "D"
mods = "Control|Shift|Alt"
chars = "\u001b[68;7u"

[[key_bindings]]
key = "E"
mods = "Control|Shift"
chars = "\u001b[69;5u"

[[key_bindings]]
key = "E"
mods = "Control|Shift|Alt"
chars = "\u001b[69;7u"

# Control + F ⇒ SearchForward
# [[key_bindings]]
# key = "F"
# mods = "Control|Shift"
# chars = "\u001b[70;5u"
[[key_bindings]]
key = "F"
mods = "Control|Shift|Alt"
chars = "\u001b[70;7u"

[[key_bindings]]
key = "G"
mods = "Control|Shift"
chars = "\u001b[71;5u"

[[key_bindings]]
key = "G"
mods = "Control|Shift|Alt"
chars = "\u001b[71;7u"

[[key_bindings]]
key = "H"
mods = "Control|Shift"
chars = "\u001b[72;5u"

[[key_bindings]]
key = "H"
mods = "Control|Shift|Alt"
chars = "\u001b[72;7u"

[[key_bindings]]
key = "I"
mods = "Control|Shift"
chars = "\u001b[73;5u"

[[key_bindings]]
key = "I"
mods = "Control|Shift|Alt"
chars = "\u001b[73;7u"

[[key_bindings]]
key = "J"
mods = "Control|Shift"
chars = "\u001b[74;5u"

[[key_bindings]]
key = "J"
mods = "Control|Shift|Alt"
chars = "\u001b[74;7u"

[[key_bindings]]
key = "K"
mods = "Control|Shift"
chars = "\u001b[75;5u"

[[key_bindings]]
key = "K"
mods = "Control|Shift|Alt"
chars = "\u001b[75;7u"

[[key_bindings]]
key = "L"
mods = "Control|Shift"
chars = "\u001b[76;5u"

[[key_bindings]]
key = "L"
mods = "Control|Shift|Alt"
chars = "\u001b[76;7u"

[[key_bindings]]
key = "M"
mods = "Control|Shift"
chars = "\u001b[77;5u"

[[key_bindings]]
key = "M"
mods = "Control|Shift|Alt"
chars = "\u001b[77;7u"

[[key_bindings]]
key = "N"
mods = "Control|Shift"
chars = "\u001b[78;5u"

[[key_bindings]]
key = "N"
mods = "Control|Shift|Alt"
chars = "\u001b[78;7u"

[[key_bindings]]
key = "O"
mods = "Control|Shift"
chars = "\u001b[79;5u"

[[key_bindings]]
key = "O"
mods = "Control|Shift|Alt"
chars = "\u001b[79;7u"

[[key_bindings]]
key = "P"
mods = "Control|Shift"
chars = "\u001b[80;5u"

[[key_bindings]]
key = "P"
mods = "Control|Shift|Alt"
chars = "\u001b[80;7u"

[[key_bindings]]
key = "Q"
mods = "Control|Shift"
chars = "\u001b[81;5u"

[[key_bindings]]
key = "Q"
mods = "Control|Shift|Alt"
chars = "\u001b[81;7u"

[[key_bindings]]
key = "R"
mods = "Control|Shift"
chars = "\u001b[82;5u"

[[key_bindings]]
key = "R"
mods = "Control|Shift|Alt"
chars = "\u001b[82;7u"

[[key_bindings]]
key = "S"
mods = "Control|Shift"
chars = "\u001b[83;5u"

[[key_bindings]]
key = "S"
mods = "Control|Shift|Alt"
chars = "\u001b[83;7u"

[[key_bindings]]
key = "T"
mods = "Control|Shift"
chars = "\u001b[84;5u"

[[key_bindings]]
key = "T"
mods = "Control|Shift|Alt"
chars = "\u001b[84;7u"

[[key_bindings]]
key = "U"
mods = "Control|Shift"
chars = "\u001b[85;5u"

[[key_bindings]]
key = "U"
mods = "Control|Shift|Alt"
chars = "\u001b[85;7u"

# Control + V ⇒ Paste
# [[key_bindings]]
# key = "V"
# mods = "Control|Shift"
# chars = "\u001b[86;5u"
[[key_bindings]]
key = "V"
mods = "Control|Shift|Alt"
chars = "\u001b[86;7u"

[[key_bindings]]
key = "W"
mods = "Control|Shift"
chars = "\u001b[87;5u"

[[key_bindings]]
key = "W"
mods = "Control|Shift|Alt"
chars = "\u001b[87;7u"

[[key_bindings]]
key = "X"
mods = "Control|Shift"
chars = "\u001b[88;5u"

[[key_bindings]]
key = "X"
mods = "Control|Shift|Alt"
chars = "\u001b[88;7u"

[[key_bindings]]
key = "Y"
mods = "Control|Shift"
chars = "\u001b[89;5u"

[[key_bindings]]
key = "Y"
mods = "Control|Shift|Alt"
chars = "\u001b[89;7u"

[[key_bindings]]
key = "Z"
mods = "Control|Shift"
chars = "\u001b[90;5u"

[[key_bindings]]
key = "Z"
mods = "Control|Shift|Alt"
chars = "\u001b[90;7u"

# ################################
# Non-Captured NumKey Combinations
# ################################
# Control + 0 ⇒ ResetFontSize
# [[key_bindings]]
# key = "Key0"
# mods = "Control"
# chars = "\u001b[48;5u"
[[key_bindings]]
key = "Key1"
mods = "Control"
chars = "\u001b[49;5u"

[[key_bindings]]
key = "Key2"
mods = "Control"
chars = "\u001b[50;5u"

[[key_bindings]]
key = "Key3"
mods = "Control"
chars = "\u001b[51;5u"

[[key_bindings]]
key = "Key4"
mods = "Control"
chars = "\u001b[52;5u"

[[key_bindings]]
key = "Key5"
mods = "Control"
chars = "\u001b[53;5u"

[[key_bindings]]
key = "Key6"
mods = "Control"
chars = "\u001b[54;5u"

[[key_bindings]]
key = "Key7"
mods = "Control"
chars = "\u001b[55;5u"

[[key_bindings]]
key = "Key8"
mods = "Control"
chars = "\u001b[56;5u"

[[key_bindings]]
key = "Key9"
mods = "Control"
chars = "\u001b[57;5u"

[[key_bindings]]
key = "Key0"
mods = "Control|Shift"
chars = "\u001b[48;6u"

[[key_bindings]]
key = "Key1"
mods = "Control|Shift"
chars = "\u001b[49;6u"

[[key_bindings]]
key = "Key2"
mods = "Control|Shift"
chars = "\u001b[50;6u"

[[key_bindings]]
key = "Key3"
mods = "Control|Shift"
chars = "\u001b[51;6u"

[[key_bindings]]
key = "Key4"
mods = "Control|Shift"
chars = "\u001b[52;6u"

[[key_bindings]]
key = "Key5"
mods = "Control|Shift"
chars = "\u001b[53;6u"

[[key_bindings]]
key = "Key6"
mods = "Control|Shift"
chars = "\u001b[54;6u"

[[key_bindings]]
key = "Key7"
mods = "Control|Shift"
chars = "\u001b[55;6u"

[[key_bindings]]
key = "Key8"
mods = "Control|Shift"
chars = "\u001b[56;6u"

[[key_bindings]]
key = "Key9"
mods = "Control|Shift"
chars = "\u001b[57;6u"
