# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  GodTian_Pinyin = {
    pname = "GodTian_Pinyin";
    version = "e21e41510b6d440389966bb0b2a70b38fafc6741";
    src = fetchFromGitHub {
      owner = "whatbeg";
      repo = "GodTian_Pinyin";
      rev = "e21e41510b6d440389966bb0b2a70b38fafc6741";
      fetchSubmodules = false;
      sha256 = "sha256-uSrj+hwai7fSJN7SWL5u80hp8nSzJ4XI5t/8s19uoV8=";
    };
    date = "2017-07-19";
  };
  acm-terminal = {
    pname = "acm-terminal";
    version = "321e05fc0398a6159925b858f46608ea07ef269e";
    src = fetchFromGitHub {
      owner = "twlz0ne";
      repo = "acm-terminal";
      rev = "321e05fc0398a6159925b858f46608ea07ef269e";
      fetchSubmodules = false;
      sha256 = "sha256-Flw07EwH9z0E3tqXs4mStICJmoHfp60ALrP1GmUmeuU=";
    };
    date = "2023-02-15";
  };
  jinx = {
    pname = "jinx";
    version = "127be5eb20ee233341fca1d1a28e6d8aceba808e";
    src = fetchFromGitHub {
      owner = "minad";
      repo = "jinx";
      rev = "127be5eb20ee233341fca1d1a28e6d8aceba808e";
      fetchSubmodules = false;
      sha256 = "sha256-wQQ92eU0CXCO0R9FLlqkGNYmuTGJMkKnmhBUQTmCeb4=";
    };
    date = "2023-05-23";
  };
  lsp-bridge = {
    pname = "lsp-bridge";
    version = "ae45301c6fb8707d3aff3612a0e82dcd089d7866";
    src = fetchFromGitHub {
      owner = "manateelazycat";
      repo = "lsp-bridge";
      rev = "ae45301c6fb8707d3aff3612a0e82dcd089d7866";
      fetchSubmodules = false;
      sha256 = "sha256-bw7XwgyETwwFbTIhorTedWup2fnYEOyNgrV2VzEBY4I=";
    };
    date = "2023-05-25";
  };
}
