# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  GodTian_Pinyin = {
    pname = "GodTian_Pinyin";
    version = "e21e41510b6d440389966bb0b2a70b38fafc6741";
    src = fetchFromGitHub {
      owner = "whatbeg";
      repo = "GodTian_Pinyin";
      rev = "e21e41510b6d440389966bb0b2a70b38fafc6741";
      fetchSubmodules = false;
      sha256 = "sha256-uSrj+hwai7fSJN7SWL5u80hp8nSzJ4XI5t/8s19uoV8=";
    };
    date = "2017-07-19";
  };
  acm-terminal = {
    pname = "acm-terminal";
    version = "0dbbd7f401da1bedd1a9146df6127233d601435b";
    src = fetchFromGitHub {
      owner = "twlz0ne";
      repo = "acm-terminal";
      rev = "0dbbd7f401da1bedd1a9146df6127233d601435b";
      fetchSubmodules = false;
      sha256 = "sha256-Opouy9A6z0YUT1zxZq1yHx+r/hwNE93JDwfa1fMWNgc=";
    };
    date = "2023-06-01";
  };
  jinx = {
    pname = "jinx";
    version = "2458dcb6039811a174aff8c784abdb552a361c4f";
    src = fetchFromGitHub {
      owner = "minad";
      repo = "jinx";
      rev = "2458dcb6039811a174aff8c784abdb552a361c4f";
      fetchSubmodules = false;
      sha256 = "sha256-XZ2Y/LftaQILej9fV6IV5rbIwvcPV45A+V1izPiCVJw=";
    };
    date = "2023-06-16";
  };
  lsp-bridge = {
    pname = "lsp-bridge";
    version = "238b5b67ac44cb96e73efa84366b2992744fbb32";
    src = fetchFromGitHub {
      owner = "manateelazycat";
      repo = "lsp-bridge";
      rev = "238b5b67ac44cb96e73efa84366b2992744fbb32";
      fetchSubmodules = false;
      sha256 = "sha256-TicmXDeucS68QlXHg/hVmMJ0iM8CopE/28N2JCTNte4=";
    };
    date = "2023-06-17";
  };
}
