# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  GodTian_Pinyin = {
    pname = "GodTian_Pinyin";
    version = "e21e41510b6d440389966bb0b2a70b38fafc6741";
    src = fetchFromGitHub {
      owner = "whatbeg";
      repo = "GodTian_Pinyin";
      rev = "e21e41510b6d440389966bb0b2a70b38fafc6741";
      fetchSubmodules = false;
      sha256 = "sha256-uSrj+hwai7fSJN7SWL5u80hp8nSzJ4XI5t/8s19uoV8=";
    };
    date = "2017-07-19";
  };
  acm-terminal = {
    pname = "acm-terminal";
    version = "0dbbd7f401da1bedd1a9146df6127233d601435b";
    src = fetchFromGitHub {
      owner = "twlz0ne";
      repo = "acm-terminal";
      rev = "0dbbd7f401da1bedd1a9146df6127233d601435b";
      fetchSubmodules = false;
      sha256 = "sha256-Opouy9A6z0YUT1zxZq1yHx+r/hwNE93JDwfa1fMWNgc=";
    };
    date = "2023-06-01";
  };
  jinx = {
    pname = "jinx";
    version = "6f09016ea0b5ecc48e9becdc85c2dc44a5db956a";
    src = fetchFromGitHub {
      owner = "minad";
      repo = "jinx";
      rev = "6f09016ea0b5ecc48e9becdc85c2dc44a5db956a";
      fetchSubmodules = false;
      sha256 = "sha256-4yNZ935UyWY2MnGcfqOam1APlooEiyyNUfyIunjvAxo=";
    };
    date = "2023-09-11";
  };
  lsp-bridge = {
    pname = "lsp-bridge";
    version = "3f7af8e9895f3a5a0cbddf917bfa0be8c0cee2ae";
    src = fetchFromGitHub {
      owner = "manateelazycat";
      repo = "lsp-bridge";
      rev = "3f7af8e9895f3a5a0cbddf917bfa0be8c0cee2ae";
      fetchSubmodules = false;
      sha256 = "sha256-rfddjxDmkOLc33OY5ZlttLsK0ZNL8G6WjsMZ0P4dyNQ=";
    };
    date = "2023-09-02";
  };
}
