# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  HPI = {
    pname = "HPI";
    version = "0.3.20230327";
    src = fetchurl {
      url = "https://pypi.org/packages/source/H/HPI/HPI-0.3.20230327.tar.gz";
      sha256 = "sha256-0QkuK8hzJL/KzZmgNSjZ+Ts6lJcmYNmSsj8cofG5/Wk=";
    };
  };
  StevenBlack-hosts = {
    pname = "StevenBlack-hosts";
    version = "adf011ee2c48bbf1514c09bc689cff31cc6df08a";
    src = fetchFromGitHub {
      owner = "StevenBlack";
      repo = "hosts";
      rev = "adf011ee2c48bbf1514c09bc689cff31cc6df08a";
      fetchSubmodules = false;
      sha256 = "sha256-laz9PhgEeFPpkNtpPLmmTwyna7KN13pb9KS+G8yp57M=";
    };
    date = "2023-05-16";
  };
  adguardhome = {
    pname = "adguardhome";
    version = "v0.107.29";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.29/AdGuardHome_linux_amd64.tar.gz";
      sha256 = "sha256-M4VfjRnrqYxKc9neIJndJoa8D44RRIjN5ItE4Ec6VKY=";
    };
  };
  brave = {
    pname = "brave";
    version = "1.51.118";
    src = fetchurl {
      url = "https://github.com/brave/brave-browser/releases/download/v1.51.118/brave-browser_1.51.118_amd64.deb";
      sha256 = "sha256-/OrnB4M6oefZ2aG2rQst8H4UZ/7vAFzyqWsn9kerb9c=";
    };
  };
  chord = {
    pname = "chord";
    version = "0.2.38";
    src = fetchurl {
      url = "https://github.com/PeterDing/chord/releases/download/v0.2.38/chord-0.2.38-linux-x86_64.AppImage";
      sha256 = "sha256-14rkxceyS0OwnOK14rICWnzLLkRB8dmqRkPq829znws=";
    };
  };
  drawio = {
    pname = "drawio";
    version = "21.2.8";
    src = fetchurl {
      url = "https://github.com/jgraph/drawio-desktop/releases/download/v21.2.8/drawio-x86_64-21.2.8.rpm";
      sha256 = "sha256-jYmD4m2Vh8rMvIRzs/iQpVugXjAxfCSfpzgJgdlKy8U=";
    };
  };
  hug = {
    pname = "hug";
    version = "2.6.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/h/hug/hug-2.6.1.tar.gz";
      sha256 = "sha256-sO2s4qy2GIc3ecnObs+RZdtU/vlcIiYvVwD83Z/rrsk=";
    };
  };
  logseq = {
    pname = "logseq";
    version = "0.9.6";
    src = fetchurl {
      url = "https://github.com/logseq/logseq/releases/download/0.9.6/logseq-linux-x64-0.9.6.AppImage";
      sha256 = "sha256-YC6oUKD48mKlX/bHWPMKm+0Ub0/5dnXmBFnVIGqzb/g=";
    };
  };
  logseq-darwin = {
    pname = "logseq-darwin";
    version = "0.9.6";
    src = fetchurl {
      url = "https://github.com/logseq/logseq/releases/download/0.9.6/logseq-darwin-x64-0.9.6.dmg";
      sha256 = "sha256-1JtXg6S0td++O0x8lzb7F2HJc6w/CYxB5krIB8Zd7I8=";
    };
  };
  magnetw = {
    pname = "magnetw";
    version = "3.1.1";
    src = fetchurl {
      url = "https://github.com/xiandanin/magnetW/releases/download/3.1.1/magnetw-3.1.1-linux.AppImage";
      sha256 = "sha256-ie6XGdd/HQCxIaLY5gGOgOXCHDJxcnaxgaO7plA5Eh8=";
    };
  };
  motrix = {
    pname = "motrix";
    version = "1.8.19";
    src = fetchurl {
      url = "https://github.com/agalwood/Motrix/releases/download/v1.8.19/Motrix-1.8.19.AppImage";
      sha256 = "sha256-oSO+VH3bZcjnXjECqZgOmsvlOONbfgOq50qVLvHdKfo=";
    };
  };
  orgparse = {
    pname = "orgparse";
    version = "0.3.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/o/orgparse/orgparse-0.3.2.tar.gz";
      sha256 = "sha256-RRBQ55rLelHGXcmbkJXq5NUL1ZhUE1T552PLTL31mlU=";
    };
  };
  promnesia = {
    pname = "promnesia";
    version = "3c33b6a2c7ee81b897e20c05e2dccbb0a5a0a49f";
    src = fetchFromGitHub {
      owner = "karlicoss";
      repo = "promnesia";
      rev = "3c33b6a2c7ee81b897e20c05e2dccbb0a5a0a49f";
      fetchSubmodules = false;
      sha256 = "sha256-m+H47FyaRslROPAKCpjA9t8kI3qVBoqDKBFkPnDOTCk=";
    };
    date = "2023-05-14";
  };
  spaceship-prompt = {
    pname = "spaceship-prompt";
    version = "0600f01c2a1f60338d4cfbef00b4b78d99f4391a";
    src = fetchFromGitHub {
      owner = "spaceship-prompt";
      repo = "spaceship-prompt";
      rev = "0600f01c2a1f60338d4cfbef00b4b78d99f4391a";
      fetchSubmodules = false;
      sha256 = "sha256-aoifMAjJvv1WAlINNkMwCCop6znxyivoD3vQDo/ZbfQ=";
    };
    date = "2023-05-17";
  };
}
